version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pets"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xzs0melf2ar6"
s3_prefix = "pets"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

