# This workflow will do a clean install of node dependencies, build the source code and deploy to S3
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy UI

on:
  push:
    branches: [ master ]
    paths:
      - 'ui/*'
  workflow_dispatch:
    inputs:
      demoSession:
        description: 'Demo Session'
        required: true
        default: 'test'
# TODO
#   pull_request:
#     branches: [ master ]

# TODO update
env:
  DEMO_SESSION: ${{ github.event.inputs.demoSession || 'test' }}
  API_BASE_URL: 'http://localhost:3000'

defaults:
  run:
    working-directory: ui

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install AWS CLI
      uses: chrislennon/action-aws-cli@v1.1
    - name: Setup .env
      run: |
        cat <<- EOF > .env
          REACT_APP_DEMO_SESSION=$DEMO_SESSION
          REACT_APP_API_BASE_URL=$API_BASE_URL
        EOF
    - run: npm ci
    - run: npm run build
    - run: npm run deploy
      env:
        AWS_DEFAULT_REGION: ap-southeast-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
