# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    paths:
      - 'ui/*'
  workflow_dispatch:
    inputs:
      demoSession:
        description: 'Demo Session'
        required: true
        default: 'test'
# TODO
#   pull_request:
#     branches: [ master ]

defaults:
  run:
    working-directory: ui

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: chrislennon/action-aws-cli@v1.1
    # TODO update
    - run: >
        echo '
        REACT_APP_DEMO_SESSION=${{ github.event.inputs.demoSession }}
        REACT_APP_API_BASE_URL=http://localhost:3000
        ' > .env
    - run: npm ci
    - run: npm run build
    - run: npm run deploy
      env:
        AWS_DEFAULT_REGION: ap-southeast-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
